config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :products
      resources :reviews
      resources :users

      root to: "products#index"
    end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get('/', {to:'welcome#index', as: :root})
  get('/about', { to: 'welcome#about', as: :about })
  get('/contact_us', { to: 'contacts#index', as: :contact })
  post('/contact_us', { to: 'contacts#create' })

  patch "/reviews/:id/toggle" => "reviews#toggle_hidden", as: "toggle_hidden"


  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
 
  resources :products do 
    resources :reviews, only: [:create, :destroy]
  end

  resources :articles, only: [:new, :create, :show, :index, :destroy, :edit]
  resources :articles

end

app/models/product.rb
class Product < ApplicationRecord
    # This is where you put validations for your application
    belongs_to :user
    has_many(:reviews, dependent: :destroy) 
    # destroy reviews belong to the product

    validates(
        :title,
        presence: true,
        uniqueness: { case_sensitive: false },
        length: { minimum: 10, maximum: 200 }
      )
    
      validates(
        :description,
        presence: true,
        length: { minimum: 10, maximum: 200 }
      )

      validates(
        :price,
        numericality: {greater_than: 0}
      )

      before_save(:set_default_capitalize)
      before_validation(:set_default_price)
      
      def set_default_price
        self.price ||= 1.0
      end
      
      def set_default_capitalize
        self.title= self.title.capitalize
      end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Product.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Product.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show] 
# authenticate_user! is found in application_controller 
before_action :set_products, only: [:edit, :update, :show, :destroy]
before_action :authorize!, only: [:edit, :update, :destroy]


  def index
      @products = Product.all
  end
  
  def new 
      @product = Product.new
  end

  def create
      @product = Product.new(product_params)
      @product.user = current_user # product_user is a variable 
      # product.user is a method 
      if @product.save
      flash[:success] = "Product was successfully listed!"
      redirect_to product_path(@product)
      else
      @product.errors
      render 'new'
      end
  end
  
  def show
      @review = Review.new
      @reviews = @product.reviews.order(created_at: :desc)
      if can? :crud, @product
        @reviews = @product.reviews.order(created_at: :desc)
      else
        @reviews = @product.reviews.where(hidden: false).order(created_at: :desc)
      end
  end

  def edit 
  end

  def update
      if @product.update(product_params)
          flash[:success] = "Product was successfully updated!"
          redirect_to product_path(@product)
      else
          render 'edit'
      end
  end

  def destroy
    flash[:danger] = "Product destoryed!"
    @product.destroy
    redirect_to products_path
  
end


  private

  def product_params
      params.require(:product).permit(:title, :description, :price)
  end

  def set_products
      @product = Product.find(params[:id]) #querying a product
  end

  def authorize! 
    flash[:danger] = "Not Authorized!"
    redirect_to root_path unless 
    can?(:crud, @product)
  end 

end

app/views/products/_form.html.erb
<%= render '/shared/errors', obj: @product%>

<div class="container-fluid offset-2">
<div class="form-group row">
    <div class="col-md-10 title-page">
        <%= form_for(@product, :html => {class:'form-horizontal', role: "form"}) do |f| %>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :title%>
            </div>
            <div class="col-sm-10">
                <%= f.text_field :title, class: "form-control", placeholder: "Name of Product", autofocus: true %>
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :description%>
            </div>
            <div class="col-sm-10">
                <%= f.text_area :description,rows:10,class: "form-control", placeholder: "Description", autofocus: true %>
            </div>
        </div>
        
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :price%>
            </div>
            <div class="col-sm-2">
                <%= f.text_field :price, class: "form-control", placeholder: "$$", autofocus: true %>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-2">
                <%= f.submit class: 'btn btn-primary btn-lg' %>
            </div>
        </div>

        <%end%>

    </div>
</div>
</div>
<div class="col-4 offset-4">
    [ <%= link_to  "Cancel create and return to product listing", products_path %> ]
    </div>

app/views/products/edit.html.erb
<br> <h1 align="center">Edit existing product listing</h1>
<%= render 'form'%>

app/views/products/index.html.erb
<h1 class="product-index" align="center">All Products List</h1>
<div class="container">
    <div class="row">
        <% @products.each do |product| %>
       
      
        <div class="col-sm-6">
            <div class="card card-body bg-light">
                <div class="product-title">
                    <%= link_to product.title, product_path(product)%>
                </div>
                <div class="product-body">
                    <%= product.description%>
                </div>
            </div>
        </div>
       


        <%end%>
    </div>
</div>

app/views/products/new.html.erb
<br>  
<h1 align="center">Make a new Product listing</h1>
<%= render 'form'%>

app/views/products/show.html.erb
<h2 align="center">Title: <%=@product.title%></h2>
<div align="center">
  <h4 class="description"><strong>Description:
    </strong></h4>
  <%= simple_format(@product.description)%>
  <hr>
  <h5 class="price"><strong>Price:
    </strong><%="$#{@product.price}"%></h5>
  <h5 class="created-at"><strong>
    </strong><%=@product.created_at%></h5>
  <div class="product-actions row">
    <%if can? :edit, @product%>
    <%= link_to  "Edit this product", edit_product_path(@product), class: "btn btn-xs btn-primary" %>
    <%end%>
    <%if can? :destroy, @product%>
    <%= link_to 'Delete this listing', product_path(@product), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-xs btn-danger ml-2"%>
    <%end%>


  </div>
</div>
<br>

<%= form_with(model: [@product, @review], local: true) do |f| %>
<% if @review.errors.any? %>
<ul>
  <% @review.errors.full_messages.each do |msg|%>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<div class="form-group text-area">
  <div class="col-sm-4">
    <%= f.text_area :body,rows:5,class: "form-control", placeholder: "Drop a review!", autofocus: true %>
  </div>

  <div class="col-sm-2">
    <%= f.text_field :rating, class: "form-control mt-3", placeholder: "Rate 1-5", autofocus: true %>
  </div>
</div>

<div class="col-sm-offset-4">
  <%= f.submit class: 'btn btn-primary create-btn' %>
</div>
<% end %>


<div class="row" align="center">

  <% @reviews.each do |review| %>
  <%= 'hidden-review' if review.hidden %>
  <div class="col-sm-4">
    <div class="product-review">
      <%= review.body %>
    </div>
    <div class="product-rating">
      <%= "Rating: #{review.rating}"%>
    </div>

    <div>
      <% if can? :crud, review %>
      <%= link_to 'Delete', product_path(review), method: :delete, data: { confirm: 'Are you sure that you want to delete this review?' } %>
      <% end %>
      <% if can? :crud, @product %>
      <%= link_to "#{review.hidden ? 'Show' : 'Hide' }", toggle_hidden_path(review), method: :patch %>
      <% end %>
    </div>
    <div class="col-sm-offset-4 col-sm-2">

    </div>

    <p class="product-answer"> Answered <%= time_ago_in_words(review.created_at) %> ago </p>

  </div>
  <% end %>