config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :products
      resources :reviews
      resources :users

      root to: "products#index"
    end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get('/', {to:'welcome#index', as: :root})
  get('/about', { to: 'welcome#about', as: :about })
  get('/contact_us', { to: 'contacts#index', as: :contact })
  post('/contact_us', { to: 'contacts#create' })

  patch "/reviews/:id/toggle" => "reviews#toggle_hidden", as: "toggle_hidden"


  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
 
  resources :products do 
    resources :reviews, only: [:create, :destroy]
  end

  resources :articles, only: [:new, :create, :show, :index, :destroy, :edit]
  resources :articles

end

app/views/layouts/_footer.html.erb
<div class="container">
<footer class="footer">
    <small>
        Copyright &copy; <a href="#">Simple Amazon clone app</a>
        by <a href="https://github.com/agamaoaljan6">Aljan Agamao</a>
    </small>
    <nav>
        <ul>
            <li>        
                <%=link_to 'Contact Us', contact_path, class: 'nav-item nav-link'%>
            </li>
            <li>
                <%=link_to 'About', about_path, class: 'nav-item nav-link'%>
            </li>
        </ul>
    </nav>
</footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-sm-10 offset-1">  <br>
    <% flash.each do |name,msg|%>
    <div class='alert alert-<%="#{name}"%>'>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
    <%end%>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <%= link_to 'CRUDMazon', root_path, class:"navbar-brand", id:"logo" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%=link_to 'Products', products_path, class: 'nav-item nav-link'%>


      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          Actions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%=link_to 'New Product', new_product_path, class: 'dropdown-item'%>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">

      <% if user_signed_in? %>
      <%=link_to 'Sign Out', session_path,method: :delete, class: 'btn btn-outline-danger my-2 my-sm-0 mr-2'%>
      <% else %>
      <%=link_to 'Sign Up', new_user_path, class: 'btn btn-outline-success my-2 my-sm-0 mr-2'%>
      <%=link_to 'Sign In', new_session_path, class: 'btn btn-outline-success my-2 my-sm-0 mr-2'%>
      <%end%>

    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amazon APP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer'%>
  </body>
</html>